// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Vue_JS_Template_AspNet_Core_3._1_Web_API1;

namespace Vue_JS_Template_AspNet_Core_3._1_Web_API1.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    partial class ApplicationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("Vue_JS_Template_AspNet_Core_3._1_Web_API1.Model.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("RoleId");

                    b.HasIndex("RoleName")
                        .IsUnique();

                    b.ToTable("Role");
                });

            modelBuilder.Entity("Vue_JS_Template_AspNet_Core_3._1_Web_API1.Model.RoleSettings", b =>
                {
                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<int>("SettingsId")
                        .HasColumnType("int");

                    b.Property<bool>("IsEnable")
                        .HasColumnType("bit");

                    b.HasKey("RoleId", "SettingsId");

                    b.HasIndex("SettingsId");

                    b.ToTable("RoleSettings");
                });

            modelBuilder.Entity("Vue_JS_Template_AspNet_Core_3._1_Web_API1.Model.Settings", b =>
                {
                    b.Property<int>("SettingsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("SettingsName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("SettingsId");

                    b.HasIndex("SettingsName")
                        .IsUnique();

                    b.ToTable("Settings");
                });

            modelBuilder.Entity("Vue_JS_Template_AspNet_Core_3._1_Web_API1.Model.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Image")
                        .HasMaxLength(65535)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("RoleIdenty")
                        .HasColumnType("int");

                    b.Property<string>("Signature")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Skype")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("RoleIdenty");

                    b.ToTable("User");
                });

            modelBuilder.Entity("Vue_JS_Template_AspNet_Core_3._1_Web_API1.Model.RoleSettings", b =>
                {
                    b.HasOne("Vue_JS_Template_AspNet_Core_3._1_Web_API1.Model.User", "User")
                        .WithMany("RoleSettingses")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Vue_JS_Template_AspNet_Core_3._1_Web_API1.Model.Settings", "Settings")
                        .WithMany("RoleSettingses")
                        .HasForeignKey("SettingsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Settings");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Vue_JS_Template_AspNet_Core_3._1_Web_API1.Model.User", b =>
                {
                    b.HasOne("Vue_JS_Template_AspNet_Core_3._1_Web_API1.Model.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleIdenty")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Vue_JS_Template_AspNet_Core_3._1_Web_API1.Model.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("Vue_JS_Template_AspNet_Core_3._1_Web_API1.Model.Settings", b =>
                {
                    b.Navigation("RoleSettingses");
                });

            modelBuilder.Entity("Vue_JS_Template_AspNet_Core_3._1_Web_API1.Model.User", b =>
                {
                    b.Navigation("RoleSettingses");
                });
#pragma warning restore 612, 618
        }
    }
}
